# Generated by Django 4.0.3 on 2022-04-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_product_price_alter_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countinStock',
            new_name='countInStock',
        ),
    ]
